[package]
name = "img-qoi"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
byteorder = "1.4.3"
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.51"
image = "0.23.14"
structopt = "0.3.25"
